### ISSUE TITLE
xf86-input-libinput と マウスの移動速度

### ISSUE THREAD

**Issue by b0101** [b0101/activity#26]
自宅も職場もApple のbluetooth magicmouseを使っていますが、自宅のマシンだけ移動がすごく遅い（毎秒のセンス回数が少ない）。色々と設定を変えても状況が変わらず、理由がよく解らなかったけど、最近開発が進んでいるので便利かと思って職場のマシンに`xf86-input-libinput`を入れてみたら、まさに自宅のマシンと同じくらい移動速度が遅くなった確か自宅のマシンには入れていたはず。そうかこいつが原因だったのか :simle:

**Comment by b0101** [comment]
削除してばっちり快適。

**Comment by b0101** [comment]
0.11でfIxされた :+1:

**Comment by 630E6617** [comment]
でも入れない方が固まることが明らかに少ない
